---
galaxy_info:
  author: Lucas Pokrywa
  description: Configuration d'update avec cron

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - cron
    - apt