all:
  vars:
    ssh_pubkey: "{{ lookup('ansible.builtin.env', 'SSH_PUBLIC_KEY_PATH') }}"
    backup_retention_days: 30
    automatic_reboot: false
    selinux:
      state: permissive
      policy: default
  children:
    managed_servers:
      vars:
        ansible_user: "{{ lookup('ansible.builtin.env', 'MANAGED_SERVERS_ANSIBLE_USER') }}"
        ansible_password: "{{ lookup('ansible.builtin.env', 'MANAGED_SERVERS_ANSIBLE_PASSWORD') }}"
      hosts:
        managed-node:
          ansible_host: 192.168.122.10
          firewall_rules:
            - port: 22
              protocol: tcp
              comment: SSH
              selinux: ssh_port_t
            - port: 80
              protocol: tcp
              comment: HTTP
              selinux_type: http_port_t
          packages:
            - nginx
            - grep
            - nano
            - podman
            - sudo
            - rsync

    backup_servers:
      vars:
        ansible_user: "{{ lookup('ansible.builtin.env', 'BACKUP_SERVERS_ANSIBLE_USER') }}"
        ansible_password: "{{ lookup('ansible.builtin.env', 'BACKUP_SERVERS_ANSIBLE_PASSWORD') }}"
      hosts:
        backup-node:
          ansible_host: 192.168.122.20
          firewall_rules: []
          packages:
            - rsync
            - sudo
