all:
  vars:
    ssh_pubkey: "{{ lookup('ansible.builtin.env', 'SSH_PUBLIC_KEY_PATH') }}"
    backup_retention_days: 30
    cron_automatic_reboot: false
    selinux_config:
      state: permissive
      policy: default
  children:
    managed_servers:
      vars:
        ansible_user: "{{ vault_managed_servers_ansible_user }}"
        ansible_password: "{{ vault_managed_servers_ansible_password }}"
      hosts:
        managed-node:
          ansible_host: 192.168.122.10
          ports_firewall_rules:
            - port: 22
              protocol: tcp
              comment: SSH
              selinux: ssh_port_t
            - port: 80
              protocol: tcp
              comment: HTTP
              selinux_type: http_port_t
          packages_list:
            - nginx
            - grep
            - nano
            - podman
            - sudo
            - rsync

    backup_servers:
      vars:
        ansible_user: "{{ vault_backup_servers_ansible_user }}"
        ansible_password: "{{ vault_backup_servers_ansible_password }}"
      hosts:
        backup-node:
          ansible_host: 192.168.122.20
          ports_firewall_rules: []
          packages_list:
            - rsync
            - sudo
