---
- name: Configuration des serveurs
  hosts: all
  become: true

  tasks:
    - name: Role SSH
      include_role:
        name: ssh

    - name: Configuration Cron
      include_role:
        name: cron

    - name: Configuration Monitor
      include_role:
        name: monitor
      tags:
        - monitor

    - name: Configuration des ports
      include_role:
        name: ports
      tags:
        - ports

    - name: Installation et Configuration des differents packages
      include_role:
        name: packages
      tags:
        - packages