---
- name: Debug des packages
  ansible.builtin.debug:
    var: packages
  tags:
    - debug

- name: Ajout des différents packages 
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"