---

- name: Ajout de cron
  ansible.builtin.package:
    name: cron
    state: present
    update_cache: true

- name: Copier le script bash
  ansible.builtin.template:
    src: update_server.sh.j2
    dest: /usr/local/bin/update_server
    owner: root
    group: root
    mode: '0755'

- name: Démarrer et activer cron
  ansible.builtin.systemd:
    name: cron
    state: started
    enabled: true

- name: Ajouter le script à cron
  ansible.builtin.cron:
    name: "Update hebdomadaire"
    minute: "{{ update_cron_minute }}"
    hour: "{{ update_cron_hour }}"
    weekday: "{{ update_cron_weekday }}"
    job: "/bin/bash /usr/local/bin/update_server >> /var/log/update_server.log 2>&1"
    user: root
