---
- name: Copie de la clé SSH
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('ansible.builtin.file', ssh_pubkey) }}"

- name: Activer l'authentification par clé SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present

- name: Désactiver l'authentification par mot de passe SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Désactiver la connexion root SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin {{ 'prohibit-password' if inventory_hostname in groups['backup_servers'] else 'no' }}"
    state: present

- name: Créer le dossier SSH de root
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'
  when: inventory_hostname in groups['managed_servers']

- name: Générer une clé SSH pour root
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    owner: root
    group: root
    mode: '0600'
  when: inventory_hostname in groups['managed_servers']

- name: Redémarrer le service SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
